[build]
  command = "npm run build"
  publish = "dist"

# /oauth2/authorization → 백엔드 (명시)
[[redirects]]
  from = "/oauth2/authorization/*"
  to   = "https://standings-few-challenges-maine.trycloudflare.com/oauth2/authorization/:splat"
  status = 200
  force  = true
  headers = { X-Forwarded-Host = "recipfree.com", X-Forwarded-Proto = "https" }  

# /api → 백엔드
[[redirects]]
  from = "/api/*"
  to   = "https://theta-protocols-artist-adelaide.trycloudflare.com/api/:splat"
  status = 200
  force  = true
  headers = { X-Forwarded-Host = "recipfree.com", X-Forwarded-Proto = "https" }

# /oauth2 → 백엔드 (Spring 내부 경로)
[[redirects]]
  from = "/oauth2/*"
  to   = "https://theta-protocols-artist-adelaide.trycloudflare.com/oauth2/:splat"
  status = 200
  force  = true
  headers = { X-Forwarded-Host = "recipfree.com", X-Forwarded-Proto = "https" }

# ★ 콜백 경로도 반드시 프록시
[[redirects]]
  from = "/login/oauth2/*"
  to   = "https://theta-protocols-artist-adelaide.trycloudflare.comlogin/oauth2/:splat"
  status = 200
  force  = true
  headers = { X-Forwarded-Host = "recipfree.com", X-Forwarded-Proto = "https" }

# 캐시 금지
[[headers]]
  for = "/oauth2/*"
  [headers.values]
    Cache-Control = "no-store"

[[headers]]
  for = "/login/oauth2/*"
  [headers.values]
    Cache-Control = "no-store"

[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-store"

# SPA 캐치올은 맨 마지막!
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
