[build]
  command = "npm run build"
  publish = "dist"


[[redirects]]
  from = "/api/*"
  to = "https://solo-abilities-granny-lp.trycloudflare.com/api/:splat"  # ⬅️ 여기 ngrok 주소 바뀌면 즉시 업데이트
  status = 200
  force = true

# SPA 라우팅
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API 응답은 캐시 금지(세션/쿠키 이슈 예방)
[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-store"