[build]
  command = "npm run build"
  publish = "dist"


[[redirects]]
  from = "/api/*"
  to = "https://took-harry-oasis-helicopter.trycloudflare.com/api/:splat"  # ⬅️ 여기 ngrok 주소 바뀌면 즉시 업데이트
  status = 200
  force = true

# SPA 라우팅
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# /oauth2 → 백엔드 (Spring이 내부적으로 쓰는 경로)
[[redirects]]
  from = "/oauth2/*"
  to   = "https://<BACKEND>/oauth2/:splat"
  status = 200
  force  = true

# /login/oauth2 → 백엔드 (Spring 콜백 경로)
[[redirects]]
  from = "/login/oauth2/*"
  to   = "https://<BACKEND>/login/oauth2/:splat"
  status = 200
  force  = true  

# API 응답은 캐시 금지(세션/쿠키 이슈 예방)
[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-store"

[functions]
directory = "netlify/functions"
node_bundler = "esbuild"   