[build]
  command = "npm run build"
  publish = "dist"

# 백엔드로 프록시 (고정: login.recipfree.com)
[[redirects]]
  from = "/oauth2/*"
  to   = "https://login.recipfree.com/oauth2/:splat"
  status = 200
  force  = true

[[redirects]]
  from = "/login/oauth2/*"
  to   = "https://login.recipfree.com/login/oauth2/:splat"
  status = 200
  force  = true

[[redirects]]
  from = "/api/*"
  to   = "https://login.recipfree.com/api/:splat"
  status = 200
  force  = true

# 캐시 금지 (응답 헤더)
[[headers]]
  for = "/oauth2/*"
  [headers.values]
    Cache-Control = "no-store"

[[headers]]
  for = "/login/oauth2/*"
  [headers.values]
    Cache-Control = "no-store"

[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-store"

# SPA 캐치올은 맨 마지막
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200
