[build]
  command = "npm run build"
  publish = "dist"

# /oauth2 → 백엔드(Cloudflare Tunnel: login.recipfree.com)
[[redirects]]
  from = "/oauth2/*"
  to   = "https://login.recipfree.com/oauth2/:splat"
  status = 200
  force  = true
  headers = { X-Forwarded-Host = "recipfree.com", X-Forwarded-Proto = "https" }

# 콜백 경로도 반드시 백엔드로
[[redirects]]
  from = "/login/oauth2/*"
  to   = "https://login.recipfree.com/login/oauth2/:splat"
  status = 200
  force  = true
  headers = { X-Forwarded-Host = "recipfree.com", X-Forwarded-Proto = "https" }

# API
[[redirects]]
  from = "/api/*"
  to   = "https://login.recipfree.com/api/:splat"
  status = 200
  force  = true
  headers = { X-Forwarded-Host = "recipfree.com", X-Forwarded-Proto = "https" }

# SPA 캐치올은 마지막
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200

# 캐시 금지 (응답 헤더)
[[headers]]
  for = "/oauth2/*"
  [headers.values]
    Cache-Control = "no-store"

[[headers]]
  for = "/login/oauth2/*"
  [headers.values]
    Cache-Control = "no-store"

[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-store"

# SPA 캐치올은 맨 마지막
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200

[[redirects]]
  from = "/static/*"
  to = "https://login.recipfree.com/static/:splat"
  status = 200
  force = true
  [redirects.headers]
    X-Forwarded-Host = "recipfree.com"
    X-Forwarded-Proto = "https"