[build]
  command = "npm run build"
  publish = "dist"

# ── 먼저: 이미지 프록시(함수) 별칭을 최우선으로 배치 ───────────────
# 프런트에서 /api/img-proxy?u=... 로 호출하면 함수로 rewrite
[[redirects]]
  from = "/api/img-proxy"
  to   = "/.netlify/functions/img-proxy"
  status = 200
  force  = true

# (선택) 오래 캐시하고 싶으면 헤더 추가
[[headers]]
  for = "/.netlify/functions/img-proxy"
  [headers.values]
    Cache-Control = "public, max-age=86400"

# ── 백엔드(Cloudflare Tunnel) 프록시 ─────────────────────────────
[[redirects]]
  from = "/oauth2/*"
  to   = "https://login.recipfree.com/oauth2/:splat"
  status = 200
  force  = true
  headers = { X-Forwarded-Host = "recipfree.com", X-Forwarded-Proto = "https" }

[[redirects]]
  from = "/login/oauth2/*"
  to   = "https://login.recipfree.com/login/oauth2/:splat"
  status = 200
  force  = true
  headers = { X-Forwarded-Host = "recipfree.com", X-Forwarded-Proto = "https" }

# ⚠️ 이 규칙은 반드시 이미지 프록시 별칭 아래에 두기!
[[redirects]]
  from = "/api/*"
  to   = "https://login.recipfree.com/api/:splat"
  status = 200
  force  = true
  headers = { X-Forwarded-Host = "recipfree.com", X-Forwarded-Proto = "https" }

# 정적 자원은 반드시 캐치올보다 먼저!
[[redirects]]
  from = "/static/*"
  to = "https://login.recipfree.com/static/:splat"
  status = 200
  force = true
  [redirects.headers]
    X-Forwarded-Host = "recipfree.com"
    X-Forwarded-Proto = "https"

# (필요시) 기타 정적 경로도 캐치올 위에 나열
# [[redirects]]
#   from = "/assets/*"
#   to = "/assets/:splat"
#   status = 200

# ── 헤더 ────────────────────────────────────────────────────────────
[[headers]]
  for = "/oauth2/*"
  [headers.values]
    Cache-Control = "no-store"

[[headers]]
  for = "/login/oauth2/*"
  [headers.values]
    Cache-Control = "no-store"

[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-store"

[[headers]]
  for = "/*"
  [headers.values]
    # 외부 이미지/동영상 허용 (+ data:, blob:)
    Content-Security-Policy = "default-src 'self' https:; img-src 'self' https: data: blob:; media-src 'self' https: data: blob:; frame-src https:; connect-src 'self' https: wss:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https:; style-src 'self' 'unsafe-inline' https:; font-src 'self' https: data:; object-src 'none'; base-uri 'self'; form-action 'self'; upgrade-insecure-requests"

# ── SPA 캐치올: 반드시 '맨 마지막' ────────────────────────────────
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200