[build]
  command = "npm run build"
  publish = "dist"

# /api → 백엔드
[[redirects]]
  from = "/api/*"
  to   = "https://url-morrison-dash-proof.trycloudflare.com/api/:splat"
  status = 200
  force  = true
  headers = { X-Forwarded-Host = "recipfree.com", X-Forwarded-Proto = "https" }

# /oauth2 → 백엔드 (Spring 내부 경로)
[[redirects]]
  from = "/oauth2/*"
  to   = "https://url-morrison-dash-proof.trycloudflare.com/oauth2/:splat"
  status = 200
  force  = true
  headers = { X-Forwarded-Host = "recipfree.com", X-Forwarded-Proto = "https" }


[[redirects]]
  from = "/api/*"
  to   = "https://url-morrison-dash-proof.trycloudflare.com/api/:splat"
  status = 200
  force  = true
  headers = { X-Forwarded-Host = "recipfree.com", X-Forwarded-Proto = "https" }

# (옵션) /oauth2, /login/oauth2 응답도 캐시 금지
[[headers]]
  for = "/oauth2/*"
  [headers.values]
    Cache-Control = "no-store"

[[headers]]
  for = "/login/oauth2/*"
  [headers.values]
    Cache-Control = "no-store"

# API 응답 캐시 금지(세션/쿠키 문제 예방)
[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-store"

# ⚠️ SPA 캐치올은 맨 마지막!
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"