

spring:
  jpa:
    hibernate:
      ddl-auto: create   # ⭐ 기존 테이블 지우고 매핑대로 다시 생성
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  profiles:
    active: prod



server:
  forward-headers-strategy: framework      # 프록시 뒤에서 Host/Proto 신뢰
  servlet:
    session:
      cookie:
        name: JSESSIONID
#        domain: recipfree.com             # 쿠키를 반드시 recipfree.com에
        path: /
        http-only: true
        secure: true
        same-site: none                     # 또는 NONE(HTTPS 필수)

openai:
  model: gpt-4.1-mini

app:
  front-base: ${FRONT_BASE:https://recipfree.com}

naver:
  client-id: ${NAVER_CLIENT_ID:}
  client-secret: ${NAVER_CLIENT_SECRET:}
  redirect-uri: ${NAVER_REDIRECT_URI:https://recipfree.com/api/auth/oauth/naver/callback}

google:
  client-id: ${GOOGLE_CLIENT_ID:}
  client-secret: ${GOOGLE_CLIENT_SECRET:}
  redirect-uri: ${GOOGLE_REDIRECT_URI:https://recipfree.com/api/auth/oauth/google/callback}

kakao:                                  # ✅ 최상위로 이동(google 밖으로)
  client-id: ${KAKAO_CLIENT_ID:}        # 카카오 REST API 키
  client-secret: ${KAKAO_CLIENT_SECRET:}# (선택) 콘솔에서 Secret 사용 ON일 때만
  redirect-uri: ${KAKAO_REDIRECT_URI:https://recipfree.com/api/auth/oauth/kakao/callback}
#
facebook:
  client-id: ${FACEBOOK_CLIENT_ID:}
  client-secret: ${FACEBOOK_CLIENT_SECRET:}
  redirect-uri: ${FACEBOOK_REDIRECT_URI:https://recipfree.com/api/auth/oauth/facebook/callback}

