# src/main/resources/application.yml
spring:
  profiles:
    active: prod

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            client-name: Naver
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            redirect-uri: "{baseUrl}/login/oauth2/code/naver"
            scope: [name, email]
            provider: naver
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: [openid, email, profile]
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-name: Kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            redirect-uri: "{baseUrl}/login/oauth2/code/kakao"
            scope: [account_email, profile_nickname]
            provider: kakao
          facebook:
            client-id: ${FACEBOOK_CLIENT_ID}
            client-secret: ${FACEBOOK_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/facebook"
            scope: [public_profile, email]
            provider: facebook
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          facebook:
            authorization-uri: https://www.facebook.com/v17.0/dialog/oauth
            token-uri: https://graph.facebook.com/v17.0/oauth/access_token
            user-info-uri: https://graph.facebook.com/me?fields=id,name,email
            user-name-attribute: id

server:
  error:
    include-message: always
    include-exception: true
    include-stacktrace: on_param
  forward-headers-strategy: framework
  servlet:
    session:
      cookie:
        name: RFSESSION               # 임의의 이름 권장
        domain: recipfree.com        # ★ 서브도메인 공유 (점 포함)
        path: /
        http-only: true
        secure: true                  # HTTPS 필수
        same-site: none               # 콜백 크로스사이트 허용

logging:
  level:
    root: info
    org.springframework.web: debug
    org.springframework.security: trace
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

app:
  front-base: ${FRONT_BASE:https://recipfree.com}
