

spring:
  mvc:
    async:
      request-timeout: 95s
  mail:
    host: ${MAIL_HOST:}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
mail:
  from: ${MAIL_FROM:no-reply@recipfree.com}   # 회신주소(발신자명은 SMTP 계정/콘솔 설정)


server:
  forward-headers-strategy: framework   # 프록시 뒤에서 HTTPS/Host 인지
  servlet:
    session:
      cookie:
        name: JSESSIONID
        http-only: true
        secure: true         # 운영(https)에서는 true
        same-site: None      # 크로스사이트 리다이렉트/요청에서도 쿠키 전송
        path: /

openai:
  model: gpt-4.1-mini

app:
  front-base: ${FRONT_BASE:https://recipfree.com}

naver:
  client-id: ${NAVER_CLIENT_ID:}
  client-secret: ${NAVER_CLIENT_SECRET:}
  redirect-uri: ${NAVER_REDIRECT_URI:https://recipfree.com/api/auth/oauth/naver/callback}

google:
  client-id: ${GOOGLE_CLIENT_ID:}
  client-secret: ${GOOGLE_CLIENT_SECRET:}
  redirect-uri: ${GOOGLE_REDIRECT_URI:https://recipfree.com/api/auth/oauth/google/callback}

kakao:                                  # ✅ 최상위로 이동(google 밖으로)
  client-id: ${KAKAO_CLIENT_ID:}        # 카카오 REST API 키
  client-secret: ${KAKAO_CLIENT_SECRET:}# (선택) 콘솔에서 Secret 사용 ON일 때만
  redirect-uri: ${KAKAO_REDIRECT_URI:https://recipfree.com/api/auth/oauth/kakao/callback}

facebook:
  client-id: ${FACEBOOK_CLIENT_ID:}
  client-secret: ${FACEBOOK_CLIENT_SECRET:}
  redirect-uri: ${FACEBOOK_REDIRECT_URI:https://recipfree.com/api/auth/oauth/facebook/callback}

