spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 12MB
  profiles:
    active: prod
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false   # 기본은 false
        show_sql: false     # 기본은 false

security: {}  # (빈 섹션 방지용; 내용 없음)

server:
  forward-headers-strategy: framework
  servlet:
    session:
      cookie:
        name: RFSESSION
        domain: recipfree.com     # 서브도메인 공유 필요 시 유지
        path: /
        http-only: true
        secure: true
        same-site: none

logging:
  level:
    root: info
    # 공통 기본값은 "조용하게"
    org.springframework: info
    org.hibernate: info

app:
  upload-dir: uploads
  front-base: ${FRONT_BASE:https://recipfree.com}
