spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            client-name: Naver
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            redirect-uri: "{baseUrl}/login/oauth2/code/naver"
            scope: [name, email]
            provider: naver

          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            client-name: Google
            scope: [openid, profile, email]   # openid 포함
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
            user-name-attribute: sub

          kakao:
            client-id: ${KAKAO_CLIENT_ID}                      # Kakao REST API Key
            client-secret: ${KAKAO_CLIENT_SECRET}              # Client secret ‘사용’이면 필수
            client-name: Kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post   # secret 사용 시 필수
            redirect-uri: "{baseUrl}/login/oauth2/code/kakao"               # https://recipfree.com/login/oauth2/code/kakao
            scope: [ profile_nickname, account_email ]
            provider: kakao

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri:        https://nid.naver.com/oauth2.0/token
            user-info-uri:    https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          kakao:                                # ⭐ 추가: Kakao 프로바이더
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri:         https://kauth.kakao.com/oauth/token
            user-info-uri:     https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

server:
  forward-headers-strategy: framework   # 그대로 OK

logging:
  level:
    root: info
    org.springframework: info
    org.springframework.security: info
    org.hibernate: warn