spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            client-name: Naver
            authorization-grant-type: authorization_code
            # ✅ 절대 URL로 고정
            redirect-uri: https://recipfree.com/login/oauth2/code/naver
            scope: name, email
            client-authentication-method: client_secret_post

          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-name: Kakao
            authorization-grant-type: authorization_code
            # ✅ 절대 URL로 고정
            redirect-uri: https://recipfree.com/login/oauth2/code/kakao
            scope: profile_nickname, account_email
            client-authentication-method: client_secret_post

          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            client-name: Google
            authorization-grant-type: authorization_code
            # ✅ 절대 URL로 고정
            redirect-uri: "https://recipfree.com/login/oauth2/code/{registrationId}"
            scope: openid, profile, email

          facebook:
            client-id: ${FACEBOOK_CLIENT_ID}
            client-secret: ${FACEBOOK_CLIENT_SECRET}
            client-name: Facebook
            authorization-grant-type: authorization_code
            # ✅ 절대 URL로 고정
            redirect-uri: https://recipfree.com/login/oauth2/code/facebook
            scope: public_profile, email

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri:         https://nid.naver.com/oauth2.0/token
            user-info-uri:     https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri:         https://kauth.kakao.com/oauth/token
            user-info-uri:     https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          facebook:
            authorization-uri: https://www.facebook.com/v18.0/dialog/oauth
            token-uri:         https://graph.facebook.com/v18.0/oauth/access_token
            user-info-uri:     https://graph.facebook.com/v18.0/me?fields=id,name,email
            user-name-attribute: id

server:
  forward-headers-strategy: framework
  servlet:
    session:
      cookie:
        name: RFSESSIONID
        domain: recipfree.com      # ✅ 세션 쿠키 도메인 고정(선택이지만 권장)
        path: /
        http-only: true
        secure: true
        same-site: LAX
      tracking-modes: cookie       # ✅ ;JSESSIONID 방지

app:
  front-base: https://recipfree.com

logging:
  level:
    com.homecook.ai_recipe: DEBUG
    org.springframework.security: DEBUG
