

spring:
  jpa:
    hibernate:
      ddl-auto: create   # ⭐ 기존 테이블 지우고 매핑대로 다시 생성
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  logging:
    level:
      your.package: debug
      org.hibernate.SQL: debug
      org.hibernate.orm.jdbc.bind: trace
      org.springframework.web: debug
      org.springframework.security: debug
  profiles:
    active: prod



server:
  forward-headers-strategy: framework      # 프록시 뒤에서 Host/Proto 신뢰
  servlet:
    session:
      cookie:
        name: JSESSIONID
#        domain: recipfree.com             # 쿠키를 반드시 recipfree.com에
        path: /
        http-only: true
        secure: true
        same-site: none                     # 또는 NONE(HTTPS 필수)

openai:
  model: gpt-4.1-mini

app:
  front-base: ${FRONT_BASE:https://recipfree.com}

naver:
  client-id: ${NAVER_CLIENT_ID:}
  client-secret: ${NAVER_CLIENT_SECRET:}
  redirect-uri: https://recipfree.com/login/oauth2/code/naver   # ✅ 변경

google:
  client-id: ${GOOGLE_CLIENT_ID:}
  client-secret: ${GOOGLE_CLIENT_SECRET:}
  redirect-uri: https://recipfree.com/login/oauth2/code/google  # ✅ 변경

kakao:
  client-id: ${KAKAO_CLIENT_ID:}
  client-secret: ${KAKAO_CLIENT_SECRET:}
  redirect-uri: https://recipfree.com/login/oauth2/code/kakao   # ✅ 변경

facebook:
  client-id: ${FACEBOOK_CLIENT_ID:}
  client-secret: ${FACEBOOK_CLIENT_SECRET:}
  redirect-uri: https://recipfree.com/login/oauth2/code/facebook # ✅ 변경

