spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: Naver
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: "https://recipfree.com/login/oauth2/code/naver"  # 기본값, prod에서 override
            scope:
              - name
              - email
              - profile_image
        provider:                         # ← registration 과 같은 level (들여쓰기 주의)
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri:          https://nid.naver.com/oauth2.0/token
            user-info-uri:      https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

server:
  forward-headers-strategy: framework

logging:
  level:
    org.springframework.security: TRACE